//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sample Security Question 1")]
        public string SecQ1 {
            get {
                return ((string)(this["SecQ1"]));
            }
            set {
                this["SecQ1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sample Security Question 2")]
        public string SecQ2 {
            get {
                return ((string)(this["SecQ2"]));
            }
            set {
                this["SecQ2"] = value;
            }
        }
        
        /// <summary>
        /// answer1
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("answer1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0867242ac694edd3b127cb1e9f9d6512")]
        public string SecA1 {
            get {
                return ((string)(this["SecA1"]));
            }
            set {
                this["SecA1"] = value;
            }
        }
        
        /// <summary>
        /// answer2
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("answer2")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("496b7cd0617ee46f2505b63e8fe7b145")]
        public string SecA2 {
            get {
                return ((string)(this["SecA2"]));
            }
            set {
                this["SecA2"] = value;
            }
        }
        
        /// <summary>
        /// passopen
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("passopen")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a1e1e7173e3dcb0bfdb312bb140cdb19")]
        public string PassOpen {
            get {
                return ((string)(this["PassOpen"]));
            }
            set {
                this["PassOpen"] = value;
            }
        }
        
        /// <summary>
        /// passclose
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("passclose")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2e5ce0761302861ea78195a28116b1cd")]
        public string PassClose {
            get {
                return ((string)(this["PassClose"]));
            }
            set {
                this["PassClose"] = value;
            }
        }
    }
}
